// AUTO-GENERATED-COMPATIBLE: This file may be regenerated by tools/llm/gen-engine.
// Hand-authored initial implementation. Pure module: no I/O, no globals, no `Math.random`.
import type {
  ConfigInput,
  Difficulty,
  Equipment,
  Exercise,
  Goal,
  MuscleGroup,
  MuscleGroupTier,
  PlanBlock,
  PlanItem,
  Scheme,
  Style,
  WorkoutPlan,
} from '../../domain/types';
import { MUSCLE_GROUP_TIER } from '../../domain/types';
import { findExercises } from '../../data/exercises';
import { createRng, type Rng } from '../../lib/rng';

// ----- Style templates -----
interface StyleTemplate {
  exerciseCount: [number, number];
  rounds: [number, number];
  isTime: boolean;
  workSec?: number;
  /** Inter-set rest within a rep-based item (ignored for time-based, sets=1). */
  withinItemRestSec: number;
  /** Inter-item rest inside a round. */
  interItemRestSec: number;
  interRoundRestSec: number;
}

const STYLE_TEMPLATES: Record<Style, StyleTemplate> = {
  straightSets: {
    exerciseCount: [4, 6],
    rounds: [1, 1],
    isTime: false,
    withinItemRestSec: 75,
    interItemRestSec: 15,
    interRoundRestSec: 0,
  },
  circuit: {
    exerciseCount: [5, 6],
    rounds: [3, 3],
    isTime: false,
    withinItemRestSec: 0,
    interItemRestSec: 30,
    interRoundRestSec: 60,
  },
  hiit: {
    exerciseCount: [6, 8],
    rounds: [3, 4],
    isTime: true,
    workSec: 40,
    withinItemRestSec: 0,
    interItemRestSec: 20,
    interRoundRestSec: 30,
  },
  tabata: {
    exerciseCount: [8, 8],
    rounds: [8, 8],
    isTime: true,
    workSec: 20,
    withinItemRestSec: 0,
    interItemRestSec: 10,
    interRoundRestSec: 0,
  },
};

// ----- Goal modifiers -----
interface GoalMod {
  reps: [number, number];
  restMul: number;
}

const GOAL_MODS: Record<Goal, GoalMod> = {
  strength: { reps: [4, 6], restMul: 1.4 },
  hypertrophy: { reps: [8, 12], restMul: 1.0 },
  endurance: { reps: [15, 20], restMul: 0.7 },
  fatLoss: { reps: [10, 15], restMul: 0.7 },
  mobility: { reps: [8, 12], restMul: 0.8 },
};

const DIFFICULTY_SCALE: Record<Difficulty, number> = {
  beginner: 0.85,
  intermediate: 1.0,
  advanced: 1.2,
};

const DIFFICULTY_RANK: Record<Difficulty, number> = {
  beginner: 0,
  intermediate: 1,
  advanced: 2,
};

/**
 * Per-tier prescription used by straight-sets style. Reflects the standard
 * dumbbell-program guidance: BIG muscles get heavier loading & longer rest,
 * AUX gets higher reps & shorter rest.
 */
interface TierScheme {
  sets: [number, number];
  reps: [number, number];
  /** Rest between sets of the SAME exercise. */
  restSec: [number, number];
}

const TIER_SCHEME: Record<MuscleGroupTier, TierScheme> = {
  big:   { sets: [3, 4], reps: [6, 10],  restSec: [90, 120] },
  small: { sets: [2, 3], reps: [8, 12],  restSec: [60, 90] },
  aux:   { sets: [2, 3], reps: [12, 20], restSec: [30, 60] },
};

/**
 * How far into a tier's rep band the goal pulls (0 = low end, 1 = high end).
 * Strength → low reps & heavier; endurance/fat-loss → high reps.
 */
const GOAL_REP_BIAS: Record<Goal, number> = {
  strength: 0.0,
  hypertrophy: 0.4,
  fatLoss: 0.7,
  endurance: 1.0,
  mobility: 0.6,
};

function exerciseTier(ex: Exercise): MuscleGroupTier {
  const primary = ex.primaryMuscles[0] ?? 'fullBody';
  return MUSCLE_GROUP_TIER[primary];
}

// ----- Helpers -----

function clamp(n: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, n));
}

function exerciseDurationSec(item: PlanItem, ex: Exercise | undefined): number {
  const s = item.scheme;
  const sideMultiplier = ex?.unilateral ? 2 : 1;
  if (s.kind === 'time') {
    return s.workSec * s.sets * sideMultiplier + s.restSec * Math.max(0, s.sets - 1);
  }
  const tempo = ex?.tempoSecPerRep ?? 3;
  return s.reps * tempo * s.sets * sideMultiplier + s.restSec * Math.max(0, s.sets - 1);
}

/**
 * Estimate total plan duration in seconds, including rests and inter-block transitions.
 */
export function estimateDurationSec(
  plan: Pick<WorkoutPlan, 'blocks'>,
  byId: ReadonlyMap<string, Exercise>,
): number {
  let total = 0;
  for (const block of plan.blocks) {
    let perRound = 0;
    for (const item of block.items) {
      perRound += exerciseDurationSec(item, byId.get(item.exerciseId));
    }
    perRound += Math.max(0, block.items.length - 1) * block.interItemRestSec;
    let blockSec = perRound * block.rounds;
    blockSec += Math.max(0, block.rounds - 1) * block.interRoundRestSec;
    total += blockSec;
  }
  total += Math.max(0, plan.blocks.length - 1) * 10;
  return Math.round(total);
}

function rangePick(rng: Rng, [a, b]: [number, number]): number {
  return a === b ? a : rng.range(a, b);
}

function withinDifficulty(ex: Exercise, target: Difficulty): boolean {
  return DIFFICULTY_RANK[ex.difficulty] <= DIFFICULTY_RANK[target];
}

function pickWithFallback(rng: Rng, pool: Exercise[], count: number): Exercise[] {
  if (pool.length === 0) return [];
  if (pool.length >= count) return rng.shuffle(pool).slice(0, count);
  const out: Exercise[] = [];
  while (out.length < count) {
    out.push(...rng.shuffle(pool));
  }
  return out.slice(0, count);
}

function buildScheme(
  rng: Rng,
  template: StyleTemplate,
  goal: Goal,
  difficulty: Difficulty,
  ex: Exercise,
  setsForItem: number,
  style: Style,
  setCap?: number,
): Scheme {
  const goalMod = GOAL_MODS[goal];
  const diffMul = DIFFICULTY_SCALE[difficulty];
  if (template.isTime) {
    const isFixed = template.workSec === 20; // tabata fixed structure
    const scale = !isFixed && goal === 'endurance' ? 1.2 : 1;
    const work = Math.max(10, Math.round((template.workSec ?? 30) * scale));
    // restSec is informational for time-based items (sets=1); inter-item rest lives on the block.
    return { kind: 'time', workSec: work, sets: 1, restSec: template.interItemRestSec };
  }
  if (ex.defaultScheme.kind === 'time') {
    return {
      kind: 'time',
      workSec: Math.max(15, Math.round(ex.defaultScheme.workSec * diffMul)),
      sets: setsForItem,
      restSec: setsForItem > 1 ? Math.round(template.withinItemRestSec * goalMod.restMul) : 0,
    };
  }

  // Straight-sets style: apply per-tier sets/reps/rest from the muscle-tier
  // prescription (BIG: 3-4×6-10 / 90-120s, SMALL: 2-3×8-12 / 60-90s,
  // AUX: 2-3×12-20 / 30-60s). Goal nudges within the tier's rep band.
  if (style === 'straightSets') {
    const tier = exerciseTier(ex);
    const prescription = TIER_SCHEME[tier];
    const setsBand = prescription.sets;
    const repsBand = prescription.reps;
    const restBand = prescription.restSec;
    const goalBias = GOAL_REP_BIAS[goal]; // 0 = low end of band, 1 = high end
    const reps = Math.max(
      3,
      Math.round(
        diffMul *
          (repsBand[0] + (repsBand[1] - repsBand[0]) * goalBias),
      ),
    );
    // Difficulty also nudges set count: advanced gets the high end, beginner the low.
    const sets =
      difficulty === 'advanced'
        ? setsBand[1]
        : difficulty === 'beginner'
          ? setsBand[0]
          : rangePick(rng, setsBand);
    const cappedSets = setCap != null ? Math.min(sets, setCap) : sets;
    const restSec =
      cappedSets > 1
        ? Math.round(restBand[0] + (restBand[1] - restBand[0]) * 0.5)
        : 0;
    return { kind: 'reps', reps, sets: cappedSets, restSec };
  }

  // Other styles (circuit/HIIT/Tabata) — keep style-template driven scheme.
  let reps = rangePick(rng, goalMod.reps);
  reps = Math.max(3, Math.round(reps * diffMul));
  const restWithin =
    setsForItem > 1 ? Math.round(template.withinItemRestSec * goalMod.restMul) : 0;
  return { kind: 'reps', reps, sets: setsForItem, restSec: restWithin };
}

function avoidConsecutiveSameMuscle(rng: Rng, exercises: Exercise[]): Exercise[] {
  if (exercises.length <= 2) return exercises;
  const distinctIds = new Set(exercises.map((e) => e.id));
  if (distinctIds.size <= 1) return exercises;
  const out = [...exercises];
  for (let attempts = 0; attempts < 20; attempts++) {
    let bad = false;
    for (let i = 1; i < out.length; i++) {
      if (
        out[i].primaryMuscles[0] &&
        out[i - 1].primaryMuscles[0] &&
        out[i].primaryMuscles[0] === out[i - 1].primaryMuscles[0]
      ) {
        const span = Math.max(1, out.length - i - 1);
        const j = (i + 1 + Math.floor(rng.next() * span)) % out.length;
        [out[i], out[j]] = [out[j], out[i]];
        bad = true;
        break;
      }
    }
    if (!bad) break;
  }
  return out;
}

function selectMain(
  rng: Rng,
  pool: Exercise[],
  bodyParts: MuscleGroup[],
  count: number,
): Exercise[] {
  if (pool.length === 0) return [];
  if (bodyParts.length === 0) {
    return rng.shuffle(pool).slice(0, Math.min(count, pool.length));
  }
  const buckets = bodyParts.map((m) =>
    rng.shuffle(
      pool.filter(
        (e) =>
          e.primaryMuscles.includes(m) ||
          e.secondaryMuscles.includes(m) ||
          e.primaryMuscles.includes('fullBody'),
      ),
    ),
  );
  const cursors = bodyParts.map(() => 0);
  const picked: Exercise[] = [];

  // Phase 1: distinct round-robin from each bucket.
  let progressed = true;
  while (picked.length < count && progressed) {
    progressed = false;
    for (let b = 0; b < buckets.length && picked.length < count; b++) {
      if (cursors[b] < buckets[b].length) {
        picked.push(buckets[b][cursors[b]]);
        cursors[b]++;
        progressed = true;
      }
    }
  }

  // Phase 2: with repeats from non-empty buckets to maintain body-part majority.
  while (picked.length < count) {
    let added = false;
    for (let b = 0; b < buckets.length && picked.length < count; b++) {
      if (buckets[b].length === 0) continue;
      picked.push(buckets[b][cursors[b] % buckets[b].length]);
      cursors[b]++;
      added = true;
    }
    if (!added) break;
  }

  // Phase 3: all buckets empty -> generic pool fallback.
  while (picked.length < count) {
    picked.push(rng.pick(pool));
  }

  return avoidConsecutiveSameMuscle(rng, picked.slice(0, count));
}

function isBodyweight(ex: Exercise): boolean {
  return ex.equipment.length === 1 && ex.equipment[0] === 'none';
}

/**
 * Quotas applied when the user targets body parts that span multiple tiers.
 * Mirrors the "pick 2-3 big, 1-2 small, fill with aux" structure used by most
 * dumbbell-based programs.
 */
const TIER_QUOTAS: Record<MuscleGroupTier, [number, number]> = {
  big: [2, 3],
  small: [1, 2],
  aux: [0, 2],
};

function classifyBodyParts(parts: MuscleGroup[]): Record<MuscleGroupTier, MuscleGroup[]> {
  const out: Record<MuscleGroupTier, MuscleGroup[]> = { big: [], small: [], aux: [] };
  for (const m of parts) out[MUSCLE_GROUP_TIER[m]].push(m);
  return out;
}

function exerciseBodyParts(ex: Exercise): MuscleGroup[] {
  return [...ex.primaryMuscles, ...ex.secondaryMuscles];
}

/**
 * When the user picks bodyParts spanning multiple tiers (e.g. chest + biceps),
 * allocate counts per tier (big: 2-3, small: 1-2, aux: fills the rest), then
 * pick distinct exercises within each tier honoring body-part focus.
 */
function selectByMuscleTierPriority(
  rng: Rng,
  pool: Exercise[],
  config: ConfigInput,
  count: number,
): Exercise[] | null {
  const tierMap = classifyBodyParts(config.bodyParts);
  const presentTiers = (Object.keys(tierMap) as MuscleGroupTier[]).filter(
    (t) => tierMap[t].length > 0,
  );
  // Only kick in when the user spans at least 2 tiers — single-tier focus uses
  // the existing flow which already round-robins evenly across selected parts.
  if (presentTiers.length < 2) return null;

  const tierPool: Record<MuscleGroupTier, Exercise[]> = { big: [], small: [], aux: [] };
  for (const ex of pool) {
    for (const tier of presentTiers) {
      if (
        tierMap[tier].some((m) => exerciseBodyParts(ex).includes(m)) ||
        ex.primaryMuscles.includes('fullBody')
      ) {
        tierPool[tier].push(ex);
        break;
      }
    }
  }

  // Initial quota: clamp to the number of distinct exercises available.
  const target: Record<MuscleGroupTier, number> = { big: 0, small: 0, aux: 0 };
  for (const tier of presentTiers) {
    const [, hi] = TIER_QUOTAS[tier];
    target[tier] = Math.min(hi, tierPool[tier].length);
  }
  let allocated = (Object.values(target) as number[]).reduce((a, b) => a + b, 0);

  // Trim oversize allocation in tier priority order: aux > small > big.
  const trimOrder: MuscleGroupTier[] = ['aux', 'small', 'big'];
  while (allocated > count) {
    let trimmed = false;
    for (const tier of trimOrder) {
      const [lo] = TIER_QUOTAS[tier];
      if (target[tier] > lo) {
        target[tier]--;
        allocated--;
        trimmed = true;
        if (allocated <= count) break;
      }
    }
    if (!trimmed) {
      // hit floors; trim aux below floor if we still must
      for (const tier of trimOrder) {
        if (target[tier] > 0 && allocated > count) {
          target[tier]--;
          allocated--;
          trimmed = true;
        }
      }
    }
    if (!trimmed) break;
  }

  // Grow allocation toward `count` if we have room (aux first, then small, then big).
  const growOrder: MuscleGroupTier[] = ['big', 'small', 'aux'];
  while (allocated < count) {
    let grew = false;
    for (const tier of growOrder) {
      if (target[tier] < tierPool[tier].length) {
        target[tier]++;
        allocated++;
        grew = true;
        if (allocated >= count) break;
      }
    }
    if (!grew) break;
  }

  // Pick distinct exercises per tier (round-robin across that tier's body parts).
  const tierPicks: Record<MuscleGroupTier, Exercise[]> = { big: [], small: [], aux: [] };
  for (const tier of presentTiers) {
    if (target[tier] === 0) continue;
    tierPicks[tier] = selectMain(rng, tierPool[tier], tierMap[tier], target[tier]);
  }

  // Interleave so order is varied but big-compounds tend to come first.
  const merged: Exercise[] = [];
  const cursors: Record<MuscleGroupTier, number> = { big: 0, small: 0, aux: 0 };
  while (merged.length < count) {
    let added = false;
    for (const tier of growOrder) {
      if (cursors[tier] < tierPicks[tier].length) {
        merged.push(tierPicks[tier][cursors[tier]++]);
        added = true;
        if (merged.length >= count) break;
      }
    }
    if (!added) break;
  }
  return merged.slice(0, count);
}

/**
 * Pick `count` main exercises while honoring `config.bodyweightRatio` against
 * the pool's bodyweight vs. equipped split. Falls back gracefully when one
 * side of the split is empty (e.g. equipment === ['none']) or when the user
 * does not request a specific share.
 */
function selectWithBodyweightRatio(
  rng: Rng,
  pool: Exercise[],
  config: ConfigInput,
  count: number,
): Exercise[] {
  // First: if the user spans multiple muscle tiers (big/small/aux), apply the
  // 2-3 BIG / 1-2 SMALL / fill-with-AUX template. This takes precedence over
  // the bodyweight ratio because muscle balance matters more than equipment mix.
  const tierPicks = selectByMuscleTierPriority(rng, pool, config, count);
  if (tierPicks && tierPicks.length === count) {
    return avoidConsecutiveSameMuscle(rng, tierPicks);
  }

  // Narrow to exercises that match the requested body parts (if any) so the
  // ratio split happens within the focused subset and doesn't dilute targeting.
  const matchesBodyPart = (e: Exercise) =>
    config.bodyParts.length === 0 ||
    config.bodyParts.some(
      (m) =>
        e.primaryMuscles.includes(m) ||
        e.secondaryMuscles.includes(m) ||
        e.primaryMuscles.includes('fullBody'),
    );
  const focused = config.bodyParts.length === 0 ? pool : pool.filter(matchesBodyPart);

  const onlyBodyweight = config.equipment.length === 1 && config.equipment[0] === 'none';
  const bwFocused = focused.filter(isBodyweight);
  const eqFocused = focused.filter((e) => !isBodyweight(e));

  // No equipment selected, or one focused side is empty -> let selectMain do its
  // existing focused round-robin (which can repeat to maintain body-part majority).
  if (onlyBodyweight || bwFocused.length === 0 || eqFocused.length === 0) {
    return selectMain(rng, pool, config.bodyParts, count);
  }

  const ratio = clamp(config.bodyweightRatio ?? 0.5, 0, 1);
  let bwCount = Math.round(count * ratio);
  let eqCount = count - bwCount;

  // Re-balance if either focused side cannot supply its share with distinct picks.
  if (bwCount > bwFocused.length) {
    eqCount += bwCount - bwFocused.length;
    bwCount = bwFocused.length;
  }
  if (eqCount > eqFocused.length) {
    bwCount += eqCount - eqFocused.length;
    eqCount = eqFocused.length;
  }
  bwCount = Math.min(bwCount, count);
  eqCount = count - bwCount;

  const bwPicks = bwCount > 0 ? selectMain(rng, bwFocused, config.bodyParts, bwCount) : [];
  const eqPicks = eqCount > 0 ? selectMain(rng, eqFocused, config.bodyParts, eqCount) : [];

  // Interleave so the order isn't "all bodyweight then all equipped".
  const merged: Exercise[] = [];
  let i = 0;
  let j = 0;
  while (merged.length < count) {
    if (i < bwPicks.length) merged.push(bwPicks[i++]);
    if (merged.length < count && j < eqPicks.length) merged.push(eqPicks[j++]);
    if (i >= bwPicks.length && j >= eqPicks.length) break;
  }
  return avoidConsecutiveSameMuscle(rng, merged.slice(0, count));
}

/**
 * Pick a single additional exercise for the duration-adjustment loop. Honors
 * the user's body-part focus, prefers exercises not already placed, and tries
 * to keep the bodyweight-vs-equipped share close to `bodyweightRatio`.
 */
function pickAdditionalExercise(
  rng: Rng,
  pool: Exercise[],
  config: ConfigInput,
  current: PlanItem[],
  usedIds: Set<string>,
): Exercise | undefined {
  const matchesBodyPart = (e: Exercise) =>
    config.bodyParts.length === 0 ||
    config.bodyParts.some(
      (m) =>
        e.primaryMuscles.includes(m) ||
        e.secondaryMuscles.includes(m) ||
        e.primaryMuscles.includes('fullBody'),
    );

  const ratio = clamp(config.bodyweightRatio ?? 0.5, 0, 1);
  const onlyBodyweight = config.equipment.length === 1 && config.equipment[0] === 'none';
  const haveBoth =
    !onlyBodyweight && pool.some(isBodyweight) && pool.some((e) => !isBodyweight(e));
  const currentBwShare =
    current.length === 0
      ? ratio
      : current.filter((it) => {
          const ex = pool.find((p) => p.id === it.exerciseId);
          return ex ? isBodyweight(ex) : false;
        }).length / current.length;
  const wantBodyweight = haveBoth ? currentBwShare < ratio : null;

  const candidates = (preferBodyweight: boolean | null) =>
    pool.filter((e) => {
      if (usedIds.has(e.id)) return false;
      if (!matchesBodyPart(e)) return false;
      if (preferBodyweight === true && !isBodyweight(e)) return false;
      if (preferBodyweight === false && isBodyweight(e)) return false;
      return true;
    });

  const tiers = [
    candidates(wantBodyweight),
    candidates(null),
    pool.filter((e) => !usedIds.has(e.id) && matchesBodyPart(e)),
    pool.filter((e) => !usedIds.has(e.id)),
  ];
  for (const tier of tiers) {
    if (tier.length > 0) return rng.pick(tier);
  }
  return undefined;
}

interface GenerateOptions {
  seed?: number;
  rng?: Rng;
}

function configHash(c: ConfigInput): number {
  const s = JSON.stringify({
    d: c.durationMin,
    b: [...c.bodyParts].sort(),
    g: c.goal,
    e: [...c.equipment].sort(),
    s: c.style,
    df: c.difficulty,
    bw: c.bodyweightRatio ?? 0.5,
  });
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function planName(c: ConfigInput): string {
  const parts: string[] = [`${c.durationMin}m`];
  if (c.bodyParts.length > 0 && c.bodyParts.length <= 3) {
    parts.push(c.bodyParts.join('+'));
  } else {
    parts.push('full body');
  }
  parts.push(c.style);
  parts.push(c.goal);
  return parts.join(' · ');
}

function poolByEquipDifficulty(
  library: readonly Exercise[],
  equip: Equipment[],
  difficulty: Difficulty,
  warmup: boolean | undefined,
  cooldown: boolean | undefined,
): Exercise[] {
  const eqOnly = findExercises(library, { equipment: equip, warmup, cooldown });
  const filtered = eqOnly.filter((e) => withinDifficulty(e, difficulty));
  return filtered.length >= 4 ? filtered : eqOnly;
}

/**
 * Generate a workout plan honoring the provided config.
 * Pure: no I/O, no Date.now (createdAt is a placeholder), no Math.random.
 */
export function generatePlan(
  config: ConfigInput,
  library: readonly Exercise[],
  options: GenerateOptions = {},
): WorkoutPlan {
  const rng = options.rng ?? createRng(options.seed ?? configHash(config));
  const byId = new Map(library.map((e) => [e.id, e]));

  const equip: Equipment[] = config.equipment.includes('none')
    ? config.equipment
    : ['none', ...config.equipment];

  const rawMainPool = poolByEquipDifficulty(library, equip, config.difficulty, false, false);
  const tabataPool = rawMainPool.filter((exercise) => !exercise.unilateral);
  const mainPool = config.style === 'tabata' && tabataPool.length >= 8 ? tabataPool : rawMainPool;
  const warmupPool = poolByEquipDifficulty(library, equip, config.difficulty, true, undefined);
  const cooldownPool = poolByEquipDifficulty(library, equip, config.difficulty, undefined, true);

  const template = STYLE_TEMPLATES[config.style];

  // Short sessions skip warmup (and tabata always skips both); cooldown stays unless tabata.
  const includeWarmup = config.style !== 'tabata' && config.durationMin >= 15;
  const includeCooldown = config.style !== 'tabata';

  const warmupBlock: PlanBlock | null =
    includeWarmup && warmupPool.length > 0
      ? {
          id: rng.uuid(),
          kind: 'warmup',
          label: 'Warm-up',
          rounds: 1,
          interItemRestSec: 0,
          interRoundRestSec: 0,
          items: pickWithFallback(rng, warmupPool, 3).map((e) => ({
            id: rng.uuid(),
            exerciseId: e.id,
            scheme: { kind: 'time', workSec: 30, sets: 1, restSec: 0 } as Scheme,
          })),
        }
      : null;

  const cooldownCount = Math.min(3, Math.max(2, cooldownPool.length || 2));
  const cooldownBlock: PlanBlock | null =
    includeCooldown && cooldownPool.length > 0
      ? {
          id: rng.uuid(),
          kind: 'cooldown',
          label: 'Cool-down',
          rounds: 1,
          interItemRestSec: 0,
          interRoundRestSec: 0,
          items: pickWithFallback(rng, cooldownPool, cooldownCount).map((e) => ({
            id: rng.uuid(),
            exerciseId: e.id,
            scheme: { kind: 'time', workSec: 40, sets: 1, restSec: 0 } as Scheme,
          })),
        }
      : null;

  const exerciseCount = rangePick(rng, template.exerciseCount);
  let rounds = rangePick(rng, template.rounds);

  // Scale rounds with duration for round-driven styles.
  if (config.style === 'tabata') {
    if (config.durationMin < 16) {
      const perRoundSec = 8 * 20 + 7 * 10;
      rounds = clamp(Math.round((config.durationMin * 60) / perRoundSec), 2, 8);
    } else {
      rounds = 8;
    }
  } else if (config.style === 'circuit') {
    rounds = config.durationMin < 15 ? 2 : clamp(Math.round(config.durationMin / 10), 3, 6);
  } else if (config.style === 'hiit') {
    rounds = config.durationMin < 15 ? 2 : clamp(Math.round(config.durationMin / 12), 3, 5);
  }

  const setsPerItem = 1;
  // Hard cap for straight-sets at short durations: per-tier prescription wants
  // 3-4 sets for BIG muscles which alone blows a 10-min budget. Cap the per-tier
  // sets count so the duration adjustment loop has room to tune.
  let setCap: number | undefined;
  if (config.style === 'straightSets') {
    if (config.durationMin < 15) setCap = 2;
    else if (config.durationMin < 30) setCap = 3;
    else if (config.durationMin < 45) setCap = 4;
    // else: no cap (use tier prescription as-is, max 4)
  }

  const buildItems = (exs: Exercise[]): PlanItem[] =>
    exs.map((ex) => ({
      id: rng.uuid(),
      exerciseId: ex.id,
      scheme: buildScheme(
        rng,
        template,
        config.goal,
        config.difficulty,
        ex,
        setsPerItem,
        config.style,
        setCap,
      ),
    }));

  const mainExercises = selectWithBodyweightRatio(
    rng,
    mainPool,
    config,
    exerciseCount,
  );
  let mainItems = buildItems(mainExercises);

  let mainBlock: PlanBlock = {
    id: rng.uuid(),
    kind: 'main',
    label: 'Main',
    rounds,
    interItemRestSec: template.interItemRestSec,
    interRoundRestSec: template.interRoundRestSec,
    items: mainItems,
  };

  const blocksOf = (m: PlanBlock): PlanBlock[] => {
    const arr: PlanBlock[] = [];
    if (warmupBlock) arr.push(warmupBlock);
    arr.push(m);
    if (cooldownBlock) arr.push(cooldownBlock);
    return arr;
  };

  const targetSec = config.durationMin * 60;

  if (config.style !== 'tabata') {
    // Long sessions need room for more items; straight-sets with beginner sets
    // (low end of tier band) at 60 min would otherwise cap at 12 items and fall short.
    const maxItems = config.durationMin >= 45 ? 18 : 12;
    let safety = 40;
    let est = estimateDurationSec({ blocks: blocksOf(mainBlock) }, byId);
    while (safety-- > 0) {
      if (est > targetSec * 1.1 && mainItems.length > 3) {
        mainItems = mainItems.slice(0, mainItems.length - 1);
      } else if (est < targetSec * 0.9 && mainItems.length < maxItems) {
        // Pick a fresh exercise that (a) honors body-part targeting and
        // (b) keeps the bodyweight-vs-equipped ratio close to target.
        const usedIds = new Set(mainItems.map((it) => it.exerciseId));
        const fresh = pickAdditionalExercise(rng, mainPool, config, mainItems, usedIds);
        const next =
          fresh ?? mainExercises[mainItems.length % Math.max(1, mainExercises.length)];
        if (!next) break;
        mainItems = [...mainItems, ...buildItems([next])];
      } else {
        break;
      }
      mainBlock = { ...mainBlock, items: mainItems };
      est = estimateDurationSec({ blocks: blocksOf(mainBlock) }, byId);
    }
  }

  const blocks = blocksOf(mainBlock);
  const estimated = estimateDurationSec({ blocks }, byId);

  return {
    id: rng.uuid(),
    createdAt: new Date(0).toISOString(),
    name: planName(config),
    config,
    blocks,
    estimatedDurationSec: clamp(estimated, 60, 60 * 180),
  };
}
