// AUTO-GENERATED-COMPATIBLE: This file may be regenerated by tools/llm/gen-engine.
// Hand-authored initial implementation. Pure module: no I/O, no globals, no `Math.random`.
import type {
  ConfigInput,
  Difficulty,
  Equipment,
  Exercise,
  Goal,
  MuscleGroup,
  PlanBlock,
  PlanItem,
  Scheme,
  Style,
  WorkoutPlan,
} from '../../domain/types';
import { findExercises } from '../../data/exercises';
import { createRng, type Rng } from '../../lib/rng';

// ----- Style templates -----
interface StyleTemplate {
  exerciseCount: [number, number];
  rounds: [number, number];
  isTime: boolean;
  workSec?: number;
  /** Inter-set rest within a rep-based item (ignored for time-based, sets=1). */
  withinItemRestSec: number;
  /** Inter-item rest inside a round. */
  interItemRestSec: number;
  interRoundRestSec: number;
}

const STYLE_TEMPLATES: Record<Style, StyleTemplate> = {
  straightSets: {
    exerciseCount: [4, 6],
    rounds: [1, 1],
    isTime: false,
    withinItemRestSec: 75,
    interItemRestSec: 15,
    interRoundRestSec: 0,
  },
  circuit: {
    exerciseCount: [5, 6],
    rounds: [3, 3],
    isTime: false,
    withinItemRestSec: 0,
    interItemRestSec: 30,
    interRoundRestSec: 60,
  },
  hiit: {
    exerciseCount: [6, 8],
    rounds: [3, 4],
    isTime: true,
    workSec: 40,
    withinItemRestSec: 0,
    interItemRestSec: 20,
    interRoundRestSec: 30,
  },
  tabata: {
    exerciseCount: [8, 8],
    rounds: [8, 8],
    isTime: true,
    workSec: 20,
    withinItemRestSec: 0,
    interItemRestSec: 10,
    interRoundRestSec: 0,
  },
};

// ----- Goal modifiers -----
interface GoalMod {
  reps: [number, number];
  restMul: number;
}

const GOAL_MODS: Record<Goal, GoalMod> = {
  strength: { reps: [4, 6], restMul: 1.4 },
  hypertrophy: { reps: [8, 12], restMul: 1.0 },
  endurance: { reps: [15, 20], restMul: 0.7 },
  fatLoss: { reps: [10, 15], restMul: 0.7 },
  mobility: { reps: [8, 12], restMul: 0.8 },
};

const DIFFICULTY_SCALE: Record<Difficulty, number> = {
  beginner: 0.85,
  intermediate: 1.0,
  advanced: 1.2,
};

const DIFFICULTY_RANK: Record<Difficulty, number> = {
  beginner: 0,
  intermediate: 1,
  advanced: 2,
};

// ----- Helpers -----

function clamp(n: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, n));
}

function exerciseDurationSec(item: PlanItem, ex: Exercise | undefined): number {
  const s = item.scheme;
  if (s.kind === 'time') return s.workSec * s.sets + s.restSec * Math.max(0, s.sets - 1);
  const tempo = ex?.tempoSecPerRep ?? 3;
  return s.reps * tempo * s.sets + s.restSec * Math.max(0, s.sets - 1);
}

/**
 * Estimate total plan duration in seconds, including rests and inter-block transitions.
 */
export function estimateDurationSec(
  plan: Pick<WorkoutPlan, 'blocks'>,
  byId: ReadonlyMap<string, Exercise>,
): number {
  let total = 0;
  for (const block of plan.blocks) {
    let perRound = 0;
    for (const item of block.items) {
      perRound += exerciseDurationSec(item, byId.get(item.exerciseId));
    }
    perRound += Math.max(0, block.items.length - 1) * block.interItemRestSec;
    let blockSec = perRound * block.rounds;
    blockSec += Math.max(0, block.rounds - 1) * block.interRoundRestSec;
    total += blockSec;
  }
  total += Math.max(0, plan.blocks.length - 1) * 10;
  return Math.round(total);
}

function rangePick(rng: Rng, [a, b]: [number, number]): number {
  return a === b ? a : rng.range(a, b);
}

function withinDifficulty(ex: Exercise, target: Difficulty): boolean {
  return DIFFICULTY_RANK[ex.difficulty] <= DIFFICULTY_RANK[target];
}

function pickWithFallback(rng: Rng, pool: Exercise[], count: number): Exercise[] {
  if (pool.length === 0) return [];
  if (pool.length >= count) return rng.shuffle(pool).slice(0, count);
  const out: Exercise[] = [];
  while (out.length < count) {
    out.push(...rng.shuffle(pool));
  }
  return out.slice(0, count);
}

function buildScheme(
  rng: Rng,
  template: StyleTemplate,
  goal: Goal,
  difficulty: Difficulty,
  ex: Exercise,
  setsForItem: number,
): Scheme {
  const goalMod = GOAL_MODS[goal];
  const diffMul = DIFFICULTY_SCALE[difficulty];
  if (template.isTime) {
    const isFixed = template.workSec === 20; // tabata fixed structure
    const scale = !isFixed && goal === 'endurance' ? 1.2 : 1;
    const work = Math.max(10, Math.round((template.workSec ?? 30) * scale));
    // restSec is informational for time-based items (sets=1); inter-item rest lives on the block.
    return { kind: 'time', workSec: work, sets: 1, restSec: template.interItemRestSec };
  }
  if (ex.defaultScheme.kind === 'time') {
    return {
      kind: 'time',
      workSec: Math.max(15, Math.round(ex.defaultScheme.workSec * diffMul)),
      sets: setsForItem,
      restSec: setsForItem > 1 ? Math.round(template.withinItemRestSec * goalMod.restMul) : 0,
    };
  }
  let reps = rangePick(rng, goalMod.reps);
  reps = Math.max(3, Math.round(reps * diffMul));
  const restWithin =
    setsForItem > 1 ? Math.round(template.withinItemRestSec * goalMod.restMul) : 0;
  return { kind: 'reps', reps, sets: setsForItem, restSec: restWithin };
}

function avoidConsecutiveSameMuscle(rng: Rng, exercises: Exercise[]): Exercise[] {
  if (exercises.length <= 2) return exercises;
  const distinctIds = new Set(exercises.map((e) => e.id));
  if (distinctIds.size <= 1) return exercises;
  const out = [...exercises];
  for (let attempts = 0; attempts < 20; attempts++) {
    let bad = false;
    for (let i = 1; i < out.length; i++) {
      if (
        out[i].primaryMuscles[0] &&
        out[i - 1].primaryMuscles[0] &&
        out[i].primaryMuscles[0] === out[i - 1].primaryMuscles[0]
      ) {
        const span = Math.max(1, out.length - i - 1);
        const j = (i + 1 + Math.floor(rng.next() * span)) % out.length;
        [out[i], out[j]] = [out[j], out[i]];
        bad = true;
        break;
      }
    }
    if (!bad) break;
  }
  return out;
}

function selectMain(
  rng: Rng,
  pool: Exercise[],
  bodyParts: MuscleGroup[],
  count: number,
): Exercise[] {
  if (pool.length === 0) return [];
  if (bodyParts.length === 0) {
    return rng.shuffle(pool).slice(0, Math.min(count, pool.length));
  }
  const buckets = bodyParts.map((m) =>
    rng.shuffle(
      pool.filter(
        (e) =>
          e.primaryMuscles.includes(m) ||
          e.secondaryMuscles.includes(m) ||
          e.primaryMuscles.includes('fullBody'),
      ),
    ),
  );
  const cursors = bodyParts.map(() => 0);
  const picked: Exercise[] = [];

  // Phase 1: distinct round-robin from each bucket.
  let progressed = true;
  while (picked.length < count && progressed) {
    progressed = false;
    for (let b = 0; b < buckets.length && picked.length < count; b++) {
      if (cursors[b] < buckets[b].length) {
        picked.push(buckets[b][cursors[b]]);
        cursors[b]++;
        progressed = true;
      }
    }
  }

  // Phase 2: with repeats from non-empty buckets to maintain body-part majority.
  while (picked.length < count) {
    let added = false;
    for (let b = 0; b < buckets.length && picked.length < count; b++) {
      if (buckets[b].length === 0) continue;
      picked.push(buckets[b][cursors[b] % buckets[b].length]);
      cursors[b]++;
      added = true;
    }
    if (!added) break;
  }

  // Phase 3: all buckets empty -> generic pool fallback.
  while (picked.length < count) {
    picked.push(rng.pick(pool));
  }

  return avoidConsecutiveSameMuscle(rng, picked.slice(0, count));
}

function isBodyweight(ex: Exercise): boolean {
  return ex.equipment.length === 1 && ex.equipment[0] === 'none';
}

/**
 * Pick `count` main exercises while honoring `config.bodyweightRatio` against
 * the pool's bodyweight vs. equipped split. Falls back gracefully when one
 * side of the split is empty (e.g. equipment === ['none']) or when the user
 * does not request a specific share.
 */
function selectWithBodyweightRatio(
  rng: Rng,
  pool: Exercise[],
  config: ConfigInput,
  count: number,
): Exercise[] {
  const bw = pool.filter(isBodyweight);
  const equipped = pool.filter((e) => !isBodyweight(e));
  // No equipped tools selected at all, or one side is empty -> nothing to balance.
  const onlyBodyweight = config.equipment.length === 1 && config.equipment[0] === 'none';
  if (onlyBodyweight || bw.length === 0 || equipped.length === 0) {
    return selectMain(rng, pool, config.bodyParts, count);
  }
  const ratio = clamp(config.bodyweightRatio ?? 0.5, 0, 1);
  let bwCount = Math.round(count * ratio);
  let eqCount = count - bwCount;

  // Re-balance if either side cannot supply its share with distinct picks.
  if (bwCount > bw.length) {
    eqCount += bwCount - bw.length;
    bwCount = bw.length;
  }
  if (eqCount > equipped.length) {
    bwCount += eqCount - equipped.length;
    eqCount = equipped.length;
  }
  bwCount = Math.min(bwCount, count);
  eqCount = count - bwCount;

  const bwPicks = bwCount > 0 ? selectMain(rng, bw, config.bodyParts, bwCount) : [];
  const eqPicks = eqCount > 0 ? selectMain(rng, equipped, config.bodyParts, eqCount) : [];

  // Interleave so the order isn't "all bodyweight then all equipped".
  const merged: Exercise[] = [];
  let i = 0;
  let j = 0;
  while (merged.length < count) {
    if (i < bwPicks.length) merged.push(bwPicks[i++]);
    if (merged.length < count && j < eqPicks.length) merged.push(eqPicks[j++]);
    if (i >= bwPicks.length && j >= eqPicks.length) break;
  }
  return avoidConsecutiveSameMuscle(rng, merged.slice(0, count));
}

interface GenerateOptions {
  seed?: number;
  rng?: Rng;
}

function configHash(c: ConfigInput): number {
  const s = JSON.stringify({
    d: c.durationMin,
    b: [...c.bodyParts].sort(),
    g: c.goal,
    e: [...c.equipment].sort(),
    s: c.style,
    df: c.difficulty,
    bw: c.bodyweightRatio ?? 0.5,
  });
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function planName(c: ConfigInput): string {
  const parts: string[] = [`${c.durationMin}m`];
  if (c.bodyParts.length > 0 && c.bodyParts.length <= 3) {
    parts.push(c.bodyParts.join('+'));
  } else {
    parts.push('full body');
  }
  parts.push(c.style);
  parts.push(c.goal);
  return parts.join(' · ');
}

function poolByEquipDifficulty(
  library: readonly Exercise[],
  equip: Equipment[],
  difficulty: Difficulty,
  warmup: boolean | undefined,
  cooldown: boolean | undefined,
): Exercise[] {
  const eqOnly = findExercises(library, { equipment: equip, warmup, cooldown });
  const filtered = eqOnly.filter((e) => withinDifficulty(e, difficulty));
  return filtered.length >= 4 ? filtered : eqOnly;
}

/**
 * Generate a workout plan honoring the provided config.
 * Pure: no I/O, no Date.now (createdAt is a placeholder), no Math.random.
 */
export function generatePlan(
  config: ConfigInput,
  library: readonly Exercise[],
  options: GenerateOptions = {},
): WorkoutPlan {
  const rng = options.rng ?? createRng(options.seed ?? configHash(config));
  const byId = new Map(library.map((e) => [e.id, e]));

  const equip: Equipment[] = config.equipment.includes('none')
    ? config.equipment
    : ['none', ...config.equipment];

  const mainPool = poolByEquipDifficulty(library, equip, config.difficulty, false, false);
  const warmupPool = poolByEquipDifficulty(library, equip, config.difficulty, true, undefined);
  const cooldownPool = poolByEquipDifficulty(library, equip, config.difficulty, undefined, true);

  const template = STYLE_TEMPLATES[config.style];

  // Short sessions skip warmup (and tabata always skips both); cooldown stays unless tabata.
  const includeWarmup = config.style !== 'tabata' && config.durationMin >= 15;
  const includeCooldown = config.style !== 'tabata';

  const warmupBlock: PlanBlock | null =
    includeWarmup && warmupPool.length > 0
      ? {
          id: rng.uuid(),
          kind: 'warmup',
          label: 'Warm-up',
          rounds: 1,
          interItemRestSec: 0,
          interRoundRestSec: 0,
          items: pickWithFallback(rng, warmupPool, 3).map((e) => ({
            id: rng.uuid(),
            exerciseId: e.id,
            scheme: { kind: 'time', workSec: 30, sets: 1, restSec: 0 } as Scheme,
          })),
        }
      : null;

  const cooldownCount = Math.min(3, Math.max(2, cooldownPool.length || 2));
  const cooldownBlock: PlanBlock | null =
    includeCooldown && cooldownPool.length > 0
      ? {
          id: rng.uuid(),
          kind: 'cooldown',
          label: 'Cool-down',
          rounds: 1,
          interItemRestSec: 0,
          interRoundRestSec: 0,
          items: pickWithFallback(rng, cooldownPool, cooldownCount).map((e) => ({
            id: rng.uuid(),
            exerciseId: e.id,
            scheme: { kind: 'time', workSec: 40, sets: 1, restSec: 0 } as Scheme,
          })),
        }
      : null;

  const exerciseCount = rangePick(rng, template.exerciseCount);
  let rounds = rangePick(rng, template.rounds);

  // Scale rounds with duration for round-driven styles.
  if (config.style === 'tabata') {
    if (config.durationMin < 16) {
      const perRoundSec = 8 * 20 + 7 * 10;
      rounds = clamp(Math.round((config.durationMin * 60) / perRoundSec), 2, 8);
    } else {
      rounds = 8;
    }
  } else if (config.style === 'circuit') {
    rounds = config.durationMin < 15 ? 2 : clamp(Math.round(config.durationMin / 10), 3, 6);
  } else if (config.style === 'hiit') {
    rounds = config.durationMin < 15 ? 2 : clamp(Math.round(config.durationMin / 12), 3, 5);
  }

  let setsPerItem = 1;
  if (config.style === 'straightSets') {
    if (config.durationMin < 15) setsPerItem = 2;
    else if (config.durationMin < 30) setsPerItem = 3;
    else if (config.durationMin < 45) setsPerItem = 4;
    else setsPerItem = 5;
  }

  const buildItems = (exs: Exercise[]): PlanItem[] =>
    exs.map((ex) => ({
      id: rng.uuid(),
      exerciseId: ex.id,
      scheme: buildScheme(rng, template, config.goal, config.difficulty, ex, setsPerItem),
    }));

  const mainExercises = selectWithBodyweightRatio(
    rng,
    mainPool,
    config,
    exerciseCount,
  );
  let mainItems = buildItems(mainExercises);

  let mainBlock: PlanBlock = {
    id: rng.uuid(),
    kind: 'main',
    label: 'Main',
    rounds,
    interItemRestSec: template.interItemRestSec,
    interRoundRestSec: template.interRoundRestSec,
    items: mainItems,
  };

  const blocksOf = (m: PlanBlock): PlanBlock[] => {
    const arr: PlanBlock[] = [];
    if (warmupBlock) arr.push(warmupBlock);
    arr.push(m);
    if (cooldownBlock) arr.push(cooldownBlock);
    return arr;
  };

  const targetSec = config.durationMin * 60;

  if (config.style !== 'tabata') {
    const maxItems = 12;
    let safety = 32;
    let est = estimateDurationSec({ blocks: blocksOf(mainBlock) }, byId);
    while (safety-- > 0) {
      if (est > targetSec * 1.2 && mainItems.length > 3) {
        mainItems = mainItems.slice(0, mainItems.length - 1);
      } else if (est < targetSec * 0.8 && mainItems.length < maxItems) {
        const next = mainExercises[mainItems.length % Math.max(1, mainExercises.length)];
        if (!next) break;
        mainItems = [...mainItems, ...buildItems([next])];
      } else {
        break;
      }
      mainBlock = { ...mainBlock, items: mainItems };
      est = estimateDurationSec({ blocks: blocksOf(mainBlock) }, byId);
    }
  }

  const blocks = blocksOf(mainBlock);
  const estimated = estimateDurationSec({ blocks }, byId);

  return {
    id: rng.uuid(),
    createdAt: new Date(0).toISOString(),
    name: planName(config),
    config,
    blocks,
    estimatedDurationSec: clamp(estimated, 60, 60 * 180),
  };
}
