#!/usr/bin/env node
/**
 * Dev-time CLI: regenerate the rule-based generator engine source.
 * The output of this CLI is reviewed and committed; the running app never invokes an LLM.
 */
import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getProvider } from '../shared/provider';
import { withFixtures, fixtureMode } from '../shared/fixture';
import { SYSTEM_PROMPT, buildUserPrompt } from './prompt';

interface Args {
  provider: string;
  model: string;
  temperature: number;
  out: string;
  promote: boolean;
  dryRun: boolean;
  audit?: string;
}

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '../../..');

function parseArgs(argv: string[]): Args {
  const args: Args = {
    provider: process.env.LLM_PROVIDER ?? 'openai',
    model: process.env.LLM_MODEL ?? 'gpt-4o-mini',
    temperature: 0.2,
    out: resolve(ROOT, 'src/features/generator/engine.generated.ts'),
    promote: false,
    dryRun: false,
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const next = () => argv[++i];
    switch (a) {
      case '--provider': args.provider = next(); break;
      case '--model': args.model = next(); break;
      case '--temperature': args.temperature = Number(next()); break;
      case '--out': args.out = resolve(next()); break;
      case '--promote': args.promote = true; break;
      case '--dry-run': args.dryRun = true; break;
      case '--audit': args.audit = resolve(next()); break;
      case '--help':
      case '-h':
        console.log('See tools/llm/gen-engine/spec.md for usage.');
        process.exit(0);
        break;
    }
  }
  return args;
}

const BANNED_RE = /\b(fetch|require|process|globalThis|Date\.now|Math\.random)\b/;

function bannedApiCheck(src: string): string[] {
  const violations: string[] = [];
  src.split('\n').forEach((line, i) => {
    if (BANNED_RE.test(line)) violations.push(`L${i + 1}: ${line.trim()}`);
  });
  return violations;
}

const HEADER = `// AUTO-GENERATED by tools/llm/gen-engine. Edit spec.md and re-run; do NOT hand-edit this file.\n`;

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const spec = readFileSync(resolve(HERE, 'spec.md'), 'utf8');
  const types = readFileSync(resolve(ROOT, 'src/domain/types.ts'), 'utf8');
  const testFile = readFileSync(resolve(ROOT, 'tests/generator.test.ts'), 'utf8');
  const testSubset = testFile.split('describe(').slice(0, 4).join('describe(');

  const provider = withFixtures(getProvider(args.provider), resolve(HERE, 'fixtures'));
  console.error(`[gen-engine] provider=${provider.name} model=${args.model} fixture=${fixtureMode()}`);

  const messages = [
    { role: 'system' as const, content: SYSTEM_PROMPT },
    { role: 'user' as const, content: buildUserPrompt({ spec, types, testSubset }) },
  ];
  const text = await provider.complete(messages, {
    model: args.model,
    temperature: args.temperature,
  });

  // Strip optional fences/prose
  let src = text.trim();
  const fence = src.match(/^```(?:ts|typescript)?\s*([\s\S]*?)```$/);
  if (fence) src = fence[1].trim();

  const violations = bannedApiCheck(src);
  const finalSrc = HEADER + src + '\n';

  if (args.dryRun) {
    process.stdout.write(finalSrc);
    if (violations.length > 0) {
      console.error('\n[gen-engine] BANNED APIS detected:');
      violations.forEach((v) => console.error('  ' + v));
      process.exit(2);
    }
    return;
  }

  mkdirSync(dirname(args.out), { recursive: true });
  writeFileSync(args.out, finalSrc, 'utf8');
  console.error(`[gen-engine] wrote candidate ${args.out}`);

  if (args.audit) {
    mkdirSync(dirname(args.audit), { recursive: true });
    writeFileSync(
      args.audit,
      JSON.stringify({ args, messages, response: text, violations }, null, 2),
      'utf8',
    );
  }

  if (violations.length > 0) {
    console.error('[gen-engine] BANNED APIS detected, refusing to promote:');
    violations.forEach((v) => console.error('  ' + v));
    process.exit(2);
  }

  if (!args.promote) {
    console.error('[gen-engine] candidate written. Re-run with --promote to overwrite engine.ts after gates.');
    return;
  }

  // Gates: tsc, vitest, eslint
  const enginePath = resolve(ROOT, 'src/features/generator/engine.ts');
  const backupPath = enginePath + '.bak';
  if (existsSync(enginePath)) renameSync(enginePath, backupPath);
  renameSync(args.out, enginePath);
  let ok = true;
  try {
    execSync('npx tsc -b', { stdio: 'inherit', cwd: ROOT });
    execSync('npx vitest run tests/generator.test.ts', { stdio: 'inherit', cwd: ROOT });
    execSync('npx eslint src/features/generator/engine.ts', { stdio: 'inherit', cwd: ROOT });
  } catch {
    ok = false;
  }
  if (!ok) {
    console.error('[gen-engine] gates failed; rolling back.');
    if (existsSync(enginePath)) renameSync(enginePath, args.out);
    if (existsSync(backupPath)) renameSync(backupPath, enginePath);
    process.exit(1);
  }
  console.error('[gen-engine] promoted candidate to engine.ts');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
